import { emptyDraft, newId } from '../engine/posting'
import type {
  Account,
  CompanyBooks,
  EquipmentUnit,
  Job,
  JobLineItem,
  LineItemMapRow,
  PaymentMethodMapRow,
  Vendor,
} from '../engine/types'
import { OVERHEAD_JOB_NAME, OVERHEAD_JOB_NUMBER } from '../engine/types'

function acct(number: string, name: string, type: Account['type'], category: string, description = ''): Account {
  return { number, name, type, category, description, active: true }
}

export const CHART_OF_ACCOUNTS: Account[] = [
  acct('1000', 'Operating Checking', 'Asset', 'Bank', 'Primary operating account'),
  acct('1010', 'Payroll Checking', 'Asset', 'Bank', 'Payroll-only checking'),
  acct('1050', 'Petty Cash', 'Asset', 'Bank', 'Office / field petty cash'),
  acct('1100', 'Accounts Receivable', 'Asset', 'Receivable', 'Billed / AR offset'),
  acct('1150', 'Retainage Receivable', 'Asset', 'Receivable', 'Held by customer'),
  acct('1200', 'Undeposited Funds', 'Asset', 'Bank', 'In transit to bank'),
  acct('1500', 'Equipment', 'Asset', 'Fixed Asset', 'Owned equipment cost'),
  acct('1510', 'Accumulated Depreciation - Equipment', 'Asset', 'Fixed Asset', 'Contra'),
  acct('1600', 'Vehicles', 'Asset', 'Fixed Asset', 'Owned vehicles'),
  acct('1610', 'Accumulated Depreciation - Vehicles', 'Asset', 'Fixed Asset', 'Contra'),

  acct('2000', 'Accounts Payable', 'Liability', 'Payable', 'Unpaid / AP offset'),
  acct('2050', 'Retainage Payable', 'Liability', 'Payable', 'Held from subcontractors'),
  acct('2100', 'Credit Card - Company', 'Liability', 'Credit Card', 'Company card offset'),
  acct('2200', 'Federal Payroll Taxes Payable', 'Liability', 'Payroll Tax', '941 / federal WH'),
  acct('2210', 'State Payroll Taxes Payable', 'Liability', 'Payroll Tax', 'State WH / SUTA'),
  acct('2220', 'FUTA Payable', 'Liability', 'Payroll Tax', 'Federal unemployment'),
  acct('2300', 'Notes Payable', 'Liability', 'Debt', 'Equipment / vehicle notes'),
  acct('2400', 'Accrued Expenses', 'Liability', 'Accrual', 'Accountant month-end accruals'),

  acct('3000', 'Owner\'s Equity', 'Equity', 'Equity', 'Member capital'),
  acct('3100', 'Owner Draws', 'Equity', 'Equity', 'Distributions'),
  acct('3200', 'Retained Earnings', 'Equity', 'Equity', 'Prior years + opening plug'),

  acct('4000', 'Construction Revenue', 'Revenue', 'Revenue', 'Progress billings'),
  acct('4100', 'Change Order Revenue', 'Revenue', 'Revenue', 'Approved COs'),
  acct('4200', 'Equipment Rental Revenue', 'Revenue', 'Revenue', 'Rare third-party rental'),
  acct('4900', 'Retainage Billed', 'Revenue', 'Revenue', 'Retainage on pay apps'),
  acct('4910', 'Other Income', 'Revenue', 'Revenue', 'Misc income'),

  acct('5000', 'Labor - Earthwork', 'Cost of Goods', 'Job Labor', ''),
  acct('5010', 'Labor - Storm Drainage', 'Cost of Goods', 'Job Labor', ''),
  acct('5020', 'Labor - Sanitary Sewer', 'Cost of Goods', 'Job Labor', ''),
  acct('5030', 'Labor - Water', 'Cost of Goods', 'Job Labor', ''),
  acct('5040', 'Labor - Paving / Roadway', 'Cost of Goods', 'Job Labor', ''),
  acct('5050', 'Labor - Concrete', 'Cost of Goods', 'Job Labor', ''),
  acct('5060', 'Labor - Erosion Control', 'Cost of Goods', 'Job Labor', ''),
  acct('5070', 'Labor - Utilities / Other', 'Cost of Goods', 'Job Labor', ''),
  acct('5080', 'Labor - Landscaping', 'Cost of Goods', 'Job Labor', ''),
  acct('5090', 'Labor - General / Mobilization', 'Cost of Goods', 'Job Labor', ''),

  acct('5100', 'Equipment - Earthwork', 'Cost of Goods', 'Job Equipment', ''),
  acct('5110', 'Equipment - Storm Drainage', 'Cost of Goods', 'Job Equipment', ''),
  acct('5120', 'Equipment - Sanitary Sewer', 'Cost of Goods', 'Job Equipment', ''),
  acct('5130', 'Equipment - Water', 'Cost of Goods', 'Job Equipment', ''),
  acct('5140', 'Equipment - Paving / Roadway', 'Cost of Goods', 'Job Equipment', ''),
  acct('5150', 'Equipment - Concrete', 'Cost of Goods', 'Job Equipment', ''),
  acct('5160', 'Equipment - Erosion Control', 'Cost of Goods', 'Job Equipment', ''),
  acct('5170', 'Equipment - Utilities / Other', 'Cost of Goods', 'Job Equipment', ''),
  acct('5180', 'Equipment - Landscaping', 'Cost of Goods', 'Job Equipment', ''),
  acct('5190', 'Equipment - General / Mobilization', 'Cost of Goods', 'Job Equipment', ''),

  acct('5200', 'Materials - Earthwork', 'Cost of Goods', 'Job Materials', ''),
  acct('5210', 'Materials - Storm Drainage', 'Cost of Goods', 'Job Materials', ''),
  acct('5220', 'Materials - Sanitary Sewer', 'Cost of Goods', 'Job Materials', ''),
  acct('5230', 'Materials - Water', 'Cost of Goods', 'Job Materials', ''),
  acct('5240', 'Materials - Paving / Roadway', 'Cost of Goods', 'Job Materials', ''),
  acct('5250', 'Materials - Concrete', 'Cost of Goods', 'Job Materials', ''),
  acct('5260', 'Materials - Erosion Control', 'Cost of Goods', 'Job Materials', ''),
  acct('5270', 'Materials - Utilities / Other', 'Cost of Goods', 'Job Materials', ''),
  acct('5280', 'Materials - Landscaping', 'Cost of Goods', 'Job Materials', ''),
  acct('5290', 'Materials - General / Mobilization', 'Cost of Goods', 'Job Materials', ''),

  acct('5300', 'Subcontractor - General', 'Cost of Goods', 'Subcontractor', ''),
  acct('5310', 'Subcontractor - Paving', 'Cost of Goods', 'Subcontractor', 'Paving 5310'),
  acct('5320', 'Subcontractor - Concrete', 'Cost of Goods', 'Subcontractor', 'Concrete 5320'),
  acct('5330', 'Subcontractor - Utilities', 'Cost of Goods', 'Subcontractor', ''),
  acct('5340', 'Subcontractor - Landscaping', 'Cost of Goods', 'Subcontractor', 'Landscaping 5340'),
  acct('5350', 'Subcontractor - Other', 'Cost of Goods', 'Subcontractor', 'Other 5350'),

  acct('5400', 'Third-Party Equipment Rental', 'Cost of Goods', 'Other Direct', ''),
  acct('5410', 'Internal Equipment Charge', 'Cost of Goods', 'Other Direct', 'Memo counterpart only — do not double-post owned hours'),
  acct('5440', 'Fuel & Oil - Field Equipment', 'Cost of Goods', 'Other Direct', 'Vendor fuel invoices, not memo gallons'),
  acct('5500', 'Dump Fees / Disposal', 'Cost of Goods', 'Other Direct', ''),
  acct('5510', 'Permits & Bonds', 'Cost of Goods', 'Other Direct', ''),
  acct('5520', 'Survey / As-Builts', 'Cost of Goods', 'Other Direct', ''),
  acct('5530', 'Testing / QC', 'Cost of Goods', 'Other Direct', ''),
  acct('5540', 'Traffic Control', 'Cost of Goods', 'Other Direct', ''),
  acct('5550', 'Temporary Facilities', 'Cost of Goods', 'Other Direct', ''),
  acct('5560', 'Other Direct Cost', 'Cost of Goods', 'Other Direct', ''),

  acct('6000', 'Office Salaries', 'Expense', 'Overhead', ''),
  acct('6010', 'Employer Payroll Tax', 'Expense', 'Overhead', ''),
  acct('6020', 'Workers Compensation', 'Expense', 'Overhead', ''),
  acct('6030', 'Employee Benefits', 'Expense', 'Overhead', ''),
  acct('6100', 'Rent', 'Expense', 'Overhead', ''),
  acct('6200', 'Insurance', 'Expense', 'Overhead', ''),
  acct('6300', 'Utilities - Office', 'Expense', 'Overhead', ''),
  acct('6400', 'Professional Fees - Accounting', 'Expense', 'Overhead', ''),
  acct('6410', 'Professional Fees - Legal', 'Expense', 'Overhead', ''),
  acct('6500', 'Office Supplies', 'Expense', 'Overhead', ''),
  acct('6600', 'Software & IT', 'Expense', 'Overhead', ''),
  acct('6700', 'Vehicle - Auto & Fuel (office)', 'Expense', 'Overhead', ''),
  acct('6800', 'Depreciation', 'Expense', 'Overhead', 'Accountant posts — not equipment memo'),
  acct('6900', 'Bank Fees', 'Expense', 'Overhead', ''),
  acct('6910', 'Interest Expense', 'Expense', 'Overhead', ''),
  acct('6920', 'Meals', 'Expense', 'Overhead', ''),
  acct('6930', 'Travel', 'Expense', 'Overhead', ''),
]

export const PAYMENT_METHOD_MAP: PaymentMethodMapRow[] = [
  { paymentMethod: 'Unpaid / AP', offsetAccount: '2000', offsetName: 'Accounts Payable' },
  { paymentMethod: 'Billed / AR', offsetAccount: '1100', offsetName: 'Accounts Receivable' },
  { paymentMethod: 'Check', offsetAccount: '1000', offsetName: 'Operating Checking' },
  { paymentMethod: 'Debit Card', offsetAccount: '1000', offsetName: 'Operating Checking' },
  { paymentMethod: 'ACH', offsetAccount: '1000', offsetName: 'Operating Checking' },
  { paymentMethod: 'Wire', offsetAccount: '1000', offsetName: 'Operating Checking' },
  { paymentMethod: 'Deposit', offsetAccount: '1000', offsetName: 'Operating Checking' },
  { paymentMethod: 'Auto-Pay', offsetAccount: '1010', offsetName: 'Payroll Checking' },
  { paymentMethod: 'Cash', offsetAccount: '1050', offsetName: 'Petty Cash' },
  { paymentMethod: 'Credit Card', offsetAccount: '2100', offsetName: 'Credit Card - Company' },
]

export const JOBS: Job[] = [
  {
    id: 'job_f001',
    jobName: 'Fern Hill',
    jobNumber: 'F001',
    status: 'Active',
    ownerCustomer: 'STYO',
    startDate: '2026-06-23',
    contractAmount: 0,
    estimatedTotalCost: 0,
    notes: 'Adding a job is a Setup row + SOV, not a new COA. Enter Keith’s contract amount here.',
    slot: 1,
  },
  {
    id: 'job_s000',
    jobName: 'Sandy Run',
    jobNumber: 'S000',
    status: 'Active',
    ownerCustomer: 'Johnston Services / Berkeley County',
    startDate: '',
    contractAmount: 0,
    estimatedTotalCost: 0,
    notes: 'SOV not loaded yet — add Job Line Items when the schedule of values is ready.',
    slot: 2,
  },
  {
    id: 'job_oh',
    jobName: OVERHEAD_JOB_NAME,
    jobNumber: OVERHEAD_JOB_NUMBER,
    status: 'Overhead',
    ownerCustomer: 'Soastal LLC',
    startDate: '',
    contractAmount: 0,
    estimatedTotalCost: 0,
    notes: 'Slot 30. Office wages, burden, rent, professional fees. Not a job cost code on a contract.',
    slot: 30,
  },
]

export const VENDORS: Vendor[] = [
  { id: 'v_vulcan', name: 'Vulcan Materials', type: 'Materials Supplier', defaultAccount: '5200', terms: 'Net 30', active: true, notes: 'Stone / ABC' },
  { id: 'v_tt', name: 'T&T', type: 'Materials Supplier', defaultAccount: '5200', terms: 'Net 30', active: true, notes: '' },
  { id: 'v_cws', name: 'Charleston Water System', type: 'Utility', defaultAccount: '5510', terms: 'Due on receipt', active: true, notes: '' },
  { id: 'v_adp', name: 'ADP / Payroll', type: 'Payroll', defaultAccount: '5090', terms: 'Auto-Pay', active: true, notes: 'Use PR- numbers; Invoice Total on first row' },
  { id: 'v_styo', name: 'STYO', type: 'Customer', defaultAccount: '4000', terms: 'Pay app', active: true, notes: 'Fern Hill owner/customer' },
  { id: 'v_johnston', name: 'Johnston Services', type: 'Customer', defaultAccount: '4000', terms: 'Pay app', active: true, notes: 'Sandy Run' },
  { id: 'v_fuel', name: 'Fuel Vendor', type: 'Equipment Dealer', defaultAccount: '5440', terms: 'Net 15', active: true, notes: 'Real fuel invoices go on Transactions' },
  { id: 'v_rental', name: 'Equipment Rental Co', type: 'Equipment Dealer', defaultAccount: '5400', terms: 'Net 30', active: true, notes: '' },
  { id: 'v_pave', name: 'Paving Subcontractor', type: 'Subcontractor', defaultAccount: '5310', terms: 'Net 30', active: true, notes: 'Override 5310' },
  { id: 'v_conc', name: 'Concrete Subcontractor', type: 'Subcontractor', defaultAccount: '5320', terms: 'Net 30', active: true, notes: 'Override 5320' },
  { id: 'v_land', name: 'Landscaping Subcontractor', type: 'Subcontractor', defaultAccount: '5340', terms: 'Net 30', active: true, notes: 'Override 5340' },
  { id: 'v_acct', name: 'Accountant', type: 'Professional', defaultAccount: '6400', terms: 'Net 15', active: true, notes: 'Professional Fees - Accounting' },
  { id: 'v_office', name: 'Office Supplier', type: 'Overhead', defaultAccount: '6500', terms: 'Credit card', active: true, notes: '' },
  { id: 'v_ins', name: 'Insurance Carrier', type: 'Overhead', defaultAccount: '6200', terms: 'Net 30', active: true, notes: '' },
]

export const EQUIPMENT: EquipmentUnit[] = [
  { id: 'eq_ex330', name: 'Excavator 330', unitNumber: 'EX-330', type: 'Excavator', ownership: 'Owned', monthlyRate: 12500, internalRatePerHour: 95, burnGalPerHour: 6.5, defaultAccount: '5410', active: true },
  { id: 'eq_ex140', name: 'Excavator 140', unitNumber: 'EX-140', type: 'Excavator', ownership: 'Owned', monthlyRate: 7800, internalRatePerHour: 62, burnGalPerHour: 4.2, defaultAccount: '5410', active: true },
  { id: 'eq_d6', name: 'Dozer D6', unitNumber: 'DZ-06', type: 'Dozer', ownership: 'Owned', monthlyRate: 11000, internalRatePerHour: 85, burnGalPerHour: 5.8, defaultAccount: '5410', active: true },
  { id: 'eq_loader', name: 'Wheel Loader', unitNumber: 'WL-01', type: 'Loader', ownership: 'Owned', monthlyRate: 8200, internalRatePerHour: 68, burnGalPerHour: 4.8, defaultAccount: '5410', active: true },
  { id: 'eq_skid', name: 'Skid Steer', unitNumber: 'SS-01', type: 'Skid Steer', ownership: 'Owned', monthlyRate: 3200, internalRatePerHour: 38, burnGalPerHour: 2.4, defaultAccount: '5410', active: true },
  { id: 'eq_roller', name: 'Smooth Drum Roller', unitNumber: 'RL-01', type: 'Compaction', ownership: 'Owned', monthlyRate: 4100, internalRatePerHour: 42, burnGalPerHour: 2.8, defaultAccount: '5410', active: true },
  { id: 'eq_dump', name: 'Tri-Axle Dump', unitNumber: 'DT-01', type: 'Truck', ownership: 'Owned', monthlyRate: 6500, internalRatePerHour: 55, burnGalPerHour: 5.0, defaultAccount: '5410', active: true },
  { id: 'eq_dump2', name: 'Tri-Axle Dump', unitNumber: 'DT-02', type: 'Truck', ownership: 'Owned', monthlyRate: 6500, internalRatePerHour: 55, burnGalPerHour: 5.0, defaultAccount: '5410', active: true },
  { id: 'eq_pickup', name: 'Superintendent Pickup', unitNumber: 'PU-01', type: 'Truck', ownership: 'Owned', monthlyRate: 1800, internalRatePerHour: 22, burnGalPerHour: 1.6, defaultAccount: '5410', active: true },
]

const ACT = [
  ['Earthwork', '5000', '5100', '5200'],
  ['Storm Drainage', '5010', '5110', '5210'],
  ['Sanitary Sewer', '5020', '5120', '5220'],
  ['Water', '5030', '5130', '5230'],
  ['Paving / Roadway', '5040', '5140', '5240'],
  ['Concrete', '5050', '5150', '5250'],
  ['Erosion Control', '5060', '5160', '5260'],
  ['Utilities / Other', '5070', '5170', '5270'],
  ['Landscaping', '5080', '5180', '5280'],
  ['General / Mobilization', '5090', '5190', '5290'],
] as const

export const LINE_ITEM_MAP: LineItemMapRow[] = ACT.map(([activity, labor, equipment, materials], i) => ({
  id: `lim_${i + 1}`,
  activity,
  laborAccount: labor,
  equipmentAccount: equipment,
  materialsAccount: materials,
}))

type SovSeed = [string, string, string, string, number]
const FERN_HILL_SOV: SovSeed[] = [
  ['1', 'Mobilization', 'LS', 'General / Mobilization', 1],
  ['2', 'Construction entrance', 'EA', 'Erosion Control', 1],
  ['3', 'Silt fence', 'LF', 'Erosion Control', 4200],
  ['4', 'Inlet protection', 'EA', 'Erosion Control', 28],
  ['5', 'Construction exit / wash rack', 'EA', 'Erosion Control', 1],
  ['6', 'Clearing and grubbing', 'AC', 'Earthwork', 18],
  ['7', 'Tree protection / selective clearing', 'LS', 'Earthwork', 1],
  ['8', 'Mass grading', 'CY', 'Earthwork', 42000],
  ['9', 'Fine grading', 'SY', 'Earthwork', 28000],
  ['10', 'Unclassified excavation', 'CY', 'Earthwork', 8500],
  ['11', 'Borrow / fill', 'CY', 'Earthwork', 6200],
  ['12', 'Proof roll / undercut', 'CY', 'Earthwork', 400],
  ['13', 'Storm pipe 15"', 'LF', 'Storm Drainage', 820],
  ['14', 'Storm pipe 18"', 'LF', 'Storm Drainage', 640],
  ['15', 'Storm pipe 24"', 'LF', 'Storm Drainage', 410],
  ['16', 'Storm pipe 30"', 'LF', 'Storm Drainage', 180],
  ['17', 'Catch basins', 'EA', 'Storm Drainage', 22],
  ['18', 'Junction boxes', 'EA', 'Storm Drainage', 8],
  ['19', 'Headwalls', 'EA', 'Storm Drainage', 4],
  ['20', 'Riprap', 'TN', 'Storm Drainage', 120],
  ['21', 'Storm manholes', 'EA', 'Storm Drainage', 6],
  ['22', 'Sanitary sewer 8"', 'LF', 'Sanitary Sewer', 2100],
  ['23', 'Sanitary sewer 10"', 'LF', 'Sanitary Sewer', 350],
  ['24', 'Sewer manholes', 'EA', 'Sanitary Sewer', 14],
  ['25', 'Sewer service laterals', 'EA', 'Sanitary Sewer', 48],
  ['26', 'Sewer testing / TV', 'LS', 'Sanitary Sewer', 1],
  ['27', 'Water main 8"', 'LF', 'Water', 2400],
  ['28', 'Water main 6"', 'LF', 'Water', 600],
  ['29', 'Fire hydrants', 'EA', 'Water', 8],
  ['30', 'Gate valves', 'EA', 'Water', 16],
  ['31', 'Water services / meters', 'EA', 'Water', 48],
  ['32', 'Testing and disinfection', 'LS', 'Water', 1],
  ['33', 'Curb and gutter', 'LF', 'Concrete', 5200],
  ['34', 'Sidewalk 4"', 'SF', 'Concrete', 6800],
  ['35', 'Driveway aprons', 'SY', 'Concrete', 420],
  ['36', 'Concrete flume / valley gutter', 'LF', 'Concrete', 180],
  ['37', 'ABC stone', 'TN', 'Paving / Roadway', 3800],
  ['38', 'Asphalt binder', 'TN', 'Paving / Roadway', 920],
  ['39', 'Asphalt surface', 'TN', 'Paving / Roadway', 640],
  ['40', 'Striping and marking', 'LS', 'Paving / Roadway', 1],
  ['41', 'Signage', 'LS', 'Paving / Roadway', 1],
  ['42', 'Traffic control', 'LS', 'Paving / Roadway', 1],
  ['43', 'Seed and mulch', 'AC', 'Landscaping', 12],
  ['44', 'Sod', 'SY', 'Landscaping', 1800],
  ['45', 'Trees / plantings', 'EA', 'Landscaping', 60],
  ['46', 'Pond / BMP grading', 'LS', 'Earthwork', 1],
  ['47', 'Outlet structure', 'EA', 'Storm Drainage', 1],
  ['48', 'Underdrain', 'LF', 'Storm Drainage', 320],
  ['49', 'As-builts / record drawings', 'LS', 'Utilities / Other', 1],
  ['50', 'Punchlist / closeout', 'LS', 'General / Mobilization', 1],
  ['51', 'Bonds and permits', 'LS', 'General / Mobilization', 1],
  ['52', 'Survey / layout', 'LS', 'Utilities / Other', 1],
]

export const JOB_LINE_ITEMS: JobLineItem[] = FERN_HILL_SOV.map(([itemNumber, description, unit, activity, bidQuantity]) => ({
  id: `sov_fh_${itemNumber}`,
  jobName: 'Fern Hill',
  itemNumber,
  description,
  unit,
  bidQuantity,
  activity,
}))

function demoBooks(): Pick<CompanyBooks, 'transactions' | 'fosterQueue' | 'openingBalances' | 'equipmentAllocations'> {
  const billId = 'txn_demo_vulcan_1'
  const billSplit = 'txn_demo_vulcan_2'
  const payId = 'txn_demo_vulcan_pmt'
  const arId = 'txn_demo_ar_1'
  const cashId = 'txn_demo_cash_1'
  const fosterBill = 'txn_demo_foster_1'

  const openingDate = '2026-07-01'
  return {
    openingBalances: [
      {
        id: 'ob_1000',
        asOfDate: openingDate,
        accountNumber: '1000',
        amount: 125000,
        memo: 'Opening operating checking — enter Keith’s true opening. Native: asset positive here as funded cash on hand.',
      },
      {
        id: 'ob_1010',
        asOfDate: openingDate,
        accountNumber: '1010',
        amount: 18000,
        memo: 'Opening payroll checking',
      },
      {
        id: 'ob_3200',
        asOfDate: openingDate,
        accountNumber: '3200',
        amount: -143000,
        memo: 'Equity plug so opening BS balances (cash in = money in = negative on equity).',
      },
    ],
    transactions: [
      emptyDraft({
        id: billId,
        postingDate: '2026-08-12',
        vendor: 'Vulcan Materials',
        invoiceNumber: 'VM-88421',
        sourceType: 'Bill / Invoice',
        invoiceDate: '2026-08-10',
        dueDate: '2026-09-09',
        paymentMethod: 'Unpaid / AP',
        invoiceTotal: 18420.5,
        allocationAmount: 12100,
        jobName: 'Fern Hill',
        costType: 'Materials',
        lineItem: 'ABC stone',
        poStatus: 'No PO Required',
        approvalStatus: 'Ready for Accountant',
        posted: true,
        notes: 'Accrual bill — hits job cost AND AP. Cash does not move.',
      }),
      emptyDraft({
        id: billSplit,
        postingDate: '2026-08-12',
        vendor: 'Vulcan Materials',
        invoiceNumber: 'VM-88421',
        sourceType: 'Bill / Invoice',
        invoiceDate: '2026-08-10',
        dueDate: '2026-09-09',
        paymentMethod: 'Unpaid / AP',
        invoiceTotal: 0,
        allocationAmount: 6320.5,
        jobName: 'Fern Hill',
        costType: 'Materials',
        lineItem: 'Riprap',
        poStatus: 'No PO Required',
        approvalStatus: 'Ready for Accountant',
        posted: true,
        notes: 'Split row — same vendor + invoice. Invoice Total on first row only.',
      }),
      emptyDraft({
        id: payId,
        postingDate: '2026-08-28',
        vendor: 'Vulcan Materials',
        invoiceNumber: 'VM-88100-PMT',
        sourceType: 'Check',
        invoiceDate: '2026-08-01',
        dueDate: '2026-08-31',
        paymentMethod: 'Check',
        checkRef: '1042',
        invoiceTotal: 6400,
        allocationAmount: 6400,
        jobName: '',
        costType: 'Liability',
        lineItem: '',
        overrideAccount: '2000 - Accounts Payable',
        poStatus: 'Not Applicable',
        approvalStatus: 'Paid',
        paidDate: '2026-08-28',
        posted: true,
        notes: 'Payment of a prior bill (VM-88100). Job blank. Not a second job cost.',
      }),
      emptyDraft({
        id: 'txn_demo_prior_bill',
        postingDate: '2026-08-01',
        vendor: 'Vulcan Materials',
        invoiceNumber: 'VM-88100',
        sourceType: 'Bill / Invoice',
        invoiceDate: '2026-08-01',
        dueDate: '2026-08-31',
        paymentMethod: 'Unpaid / AP',
        invoiceTotal: 6400,
        allocationAmount: 6400,
        jobName: 'Fern Hill',
        costType: 'Materials',
        lineItem: 'ABC stone',
        poStatus: 'No PO Required',
        approvalStatus: 'Ready for Accountant',
        posted: true,
        notes: 'Original bill that VM-88100-PMT cleared.',
      }),
      emptyDraft({
        id: arId,
        postingDate: '2026-08-31',
        vendor: 'STYO',
        invoiceNumber: 'FH-PAYAPP-01',
        sourceType: 'Bill / Invoice',
        invoiceDate: '2026-08-31',
        dueDate: '2026-09-30',
        paymentMethod: 'Billed / AR',
        invoiceTotal: -125000,
        allocationAmount: -125000,
        jobName: 'Fern Hill',
        costType: 'Revenue',
        lineItem: '',
        overrideAccount: '4000 - Construction Revenue',
        poStatus: 'Not Applicable',
        approvalStatus: 'Ready for Accountant',
        posted: true,
        notes: 'Customer billing. Negative allocation. Offset 1100. Deposit later clears AR.',
      }),
      emptyDraft({
        id: cashId,
        postingDate: '2026-08-15',
        vendor: 'Office Supplier',
        invoiceNumber: 'OS-2291',
        sourceType: 'Cash Purchase',
        invoiceDate: '2026-08-15',
        dueDate: '2026-08-15',
        paymentMethod: 'Debit Card',
        checkRef: 'DC-0815',
        invoiceTotal: 214.88,
        allocationAmount: 214.88,
        jobName: OVERHEAD_JOB_NAME,
        costType: 'Overhead',
        overrideAccount: '6500 - Office Supplies',
        poStatus: 'No PO Required',
        approvalStatus: 'Paid',
        paidDate: '2026-08-15',
        posted: true,
        notes: 'Paid on the spot — never AP.',
      }),
      emptyDraft({
        id: fosterBill,
        postingDate: '2026-09-01',
        vendor: 'T&T',
        invoiceNumber: 'TT-1044',
        sourceType: 'Bill / Invoice',
        invoiceDate: '2026-08-29',
        dueDate: '2026-09-28',
        paymentMethod: 'Unpaid / AP',
        invoiceTotal: 8750,
        allocationAmount: 8750,
        jobName: 'Fern Hill',
        costType: 'Materials',
        lineItem: 'Storm pipe 18"',
        poStatus: 'Missing - Get Approval',
        approvalStatus: 'Needs Approval',
        posted: false,
        notes: 'No PO on this bill — waiting on Foster yes/no before post.',
      }),
    ],
    fosterQueue: [
      {
        id: 'foster_demo_1',
        createdAt: '2026-09-01T12:00:00.000Z',
        kind: 'coding-confirm',
        transactionIds: [fosterBill],
        vendor: 'T&T',
        invoiceNumber: 'TT-1044',
        jobName: 'Fern Hill',
        proposedAccounts: ['5210 / offset 2000'],
        amount: 8750,
        reason: 'Vendor bill has no PO. Foster is the only human for invoice coding confirms.',
        decision: 'pending',
        decidedAt: '',
        fosterNote: '',
        paymentDate: '',
        paymentRef: '',
      },
    ],
    equipmentAllocations: [
      {
        id: newId('eal'),
        date: '2026-08-20',
        jobName: 'Fern Hill',
        equipmentId: 'eq_ex330',
        hours: 8.5,
        notes: 'MEMO only — internal hours × rate + fuel. Do not also post these dollars on Transactions unless a real vendor invoice exists.',
      },
    ],
  }
}

export function createEmptyBooks(): CompanyBooks {
  const demo = demoBooks()
  return {
    version: 1,
    companyName: 'Soastal LLC',
    savedAt: null,
    chartOfAccounts: CHART_OF_ACCOUNTS,
    jobs: JOBS,
    vendors: VENDORS,
    equipment: EQUIPMENT,
    lineItemMap: LINE_ITEM_MAP,
    jobLineItems: JOB_LINE_ITEMS,
    paymentMethodMap: PAYMENT_METHOD_MAP,
    transactions: demo.transactions,
    equipmentAllocations: demo.equipmentAllocations,
    openingBalances: demo.openingBalances,
    fosterQueue: demo.fosterQueue,
    periodCloses: [],
  }
}

/** Fresh books with master data only — no demo journal. */
export function createMasterDataOnly(): CompanyBooks {
  return {
    ...createEmptyBooks(),
    transactions: [],
    fosterQueue: [],
    equipmentAllocations: [],
    openingBalances: [],
  }
}
